#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    cp=0
    cn=0
    zero=0
    for i in arr:
        if i>0:
            cp+=1
        elif i<0:
            cn+=1
        else:
            zero+=1
    print(f"{cp/len(arr):6f}\n{cn/len(arr):6f}\n{zero/len(arr):6f}")
            
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
